In [3]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset = pd.get_dummies(dataset,dtype=int)

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='str')

In [9]:
indepentVar = dataset[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]

In [10]:
indepentVar

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0           1         0          0           1
1      18  33.770         1           0         1          1           0
2      28  33.000         3           0         1          1           0
3      33  22.705         0           0         1          1           0
4      32  28.880         0           0         1          1           0
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3           0         1          1           0
1334   18  31.920         0           1         0          1           0
1335   18  36.850         0           1         0          1           0
1336   21  25.800         0           1         0          1           0
1337   61  29.070         0           1         0          0           1

[1338 rows x 7 columns]

In [11]:
depententVar = dataset[['charges']]

In [12]:
depententVar

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepentVar,depententVar,test_size=0.30,random_state=0)

In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100,random_state=0)
regressor.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(random_state=0)

In [22]:
y_pred = regressor.predict(x_test)

In [23]:
y_pred

array([12108.9412435 ,  9392.6266607 , 44788.6568751 , 12930.3778475 ,
        9889.1650251 , 11739.8971948 ,  1824.2795215 , 11924.2271266 ,
        7128.79051   ,  5207.2226735 ,  7654.0991554 , 17373.3979305 ,
       10144.1352664 ,  7144.8619209 , 24265.939392  , 13273.5298093 ,
       14566.6551924 ,  3800.5341217 ,  6351.329163  , 33939.8565643 ,
       23888.3563405 , 16414.4249127 , 11225.6396097 , 27172.4636955 ,
        2950.0215188 ,  6036.4969941 ,  6091.7199957 ,  7994.23862   ,
        3708.506759  ,  9493.0663569 ,  7770.6336478 , 48353.4836454 ,
       13932.535246  , 12655.0089677 , 17015.6588863 ,  4084.2302062 ,
        8984.0357892 , 37715.8226822 , 39585.456355  ,  2806.6235224 ,
        9884.6944001 ,  4911.8101088 , 20348.547012  , 47689.3375545 ,
       37497.3684947 ,  3396.9516828 , 13286.8089638 ,  6568.8857915 ,
        5052.188558  , 12438.6337706 ,  4268.3432767 ,  4717.3625683 ,
       25903.5617002 , 49505.8871494 , 11741.7526195 , 10956.1792337 ,
        4277.1338993 , 10656.7163104 , 10289.7998363 , 16704.9919034 ,
        1620.001949  , 46957.9824736 , 15757.5191023 , 19256.4468494 ,
       11428.3005696 ,  9876.1015865 , 33912.9297137 , 39824.4726842 ,
        3213.5118809 , 11303.1426485 , 18039.464138  , 12660.1340225 ,
       17355.5222192 , 14120.2688751 , 14007.4062598 , 15610.8469105 ,
        7739.1034327 , 15700.2956309 , 19538.2160375 , 46625.047755  ,
       11558.3857805 , 49640.2135622 ,  4494.7866516 ,  9736.7755836 ,
       40480.0313457 , 19348.1589627 ,  4010.9751672 ,  3933.3566289 ,
       14058.4977405 , 39627.7169058 ,  5790.3771847 , 13473.623647  ,
        2903.7774555 , 10170.6048449 ,  9737.9326235 ,  4162.436547  ,
       43168.1446026 , 53248.5946729 ,  5572.4723536 , 10989.6448635 ,
        2793.575341  ,  8373.7525256 ,  7807.3915479 , 39943.3725799 ,
       28557.7036308 ,  4954.2983999 , 11244.525525  ,  7166.4079105 ,
       11624.2577525 , 45441.019171  , 12263.5734684 ,  7098.5917158 ,
        9928.9079587 , 34467.3414344 , 47896.3868394 ,  7124.138204  ,
        2279.047587  , 10743.0140789 , 22756.6144349 ,  9340.0449244 ,
       41872.1208218 , 12337.5650369 , 14615.0046065 ,  8759.4580152 ,
       11156.2307452 ,  5484.1017894 , 26916.0743914 , 26077.8136428 ,
       48362.8590539 ,  1724.9657901 , 16056.6438276 ,  3720.7149611 ,
        6169.9791238 ,  9063.0825305 , 44736.5386119 , 38106.9543666 ,
       24680.2989163 , 15448.0575885 , 24736.1544402 ,  6405.485999  ,
        2000.626241  , 12228.9448479 , 10554.3690308 , 10862.7763589 ,
        7088.7270422 , 14308.046796  , 23736.4567252 , 14432.3130705 ,
        1545.959465  , 12565.2446116 ,  6243.230386  , 39235.2121174 ,
       10078.3678081 ,  9107.7957511 ,  4033.3528605 ,  8766.9861891 ,
        3613.0222049 ,  7193.3333709 , 13273.5298093 , 10308.7911682 ,
        6829.4774759 , 13218.698536  , 14368.3970743 ,  9216.3013295 ,
        4451.5479188 , 10761.2859768 , 16753.6505033 ,  6312.2301456 ,
        4351.6716252 ,  2086.5665285 ,  6956.5253338 ,  6602.590764  ,
       11604.7475757 ,  2858.0252393 , 10564.3076173 , 10978.6691306 ,
        5106.9007756 ,  6879.1066355 , 26894.315874  ,  1641.6918105 ,
       17174.3281677 ,  6767.0536588 , 11435.011189  ,  8134.0776986 ,
        9941.6606354 , 27884.046472  ,  4321.889222  ,  3576.4772423 ,
       14191.901909  , 10790.8591869 , 41182.78648   ,  5032.2882011 ,
        5351.1960925 , 24446.0636081 ,  3217.1148065 ,  3180.6093884 ,
        9825.99234   ,  6077.7812608 ,  9924.9937199 ,  4324.993236  ,
       12441.2205364 , 46723.4741201 , 17930.4459036 , 19028.602087  ,
       11296.7138673 , 43747.5346226 ,  4517.245159  , 10487.0875648 ,
        6411.0901065 ,  1994.210892  ,  9676.002029  , 13660.342873  ,
        7222.9564543 ,  4624.3201887 ,  6501.789499  , 10310.853774  ,
        6626.7915622 ,  6470.8811841 , 14184.8288853 ,  6853.1742649 ,
       13717.1940547 ,  7818.089224  , 11451.9281998 ,  7119.0922329 ,
       14007.0799385 , 14362.6444345 , 21919.3293551 , 11980.9801915 ,
        7176.0523326 ,  2829.4748142 , 10710.3354425 ,  8150.865472  ,
       15328.7911305 ,  6677.8414229 ,  5663.3332993 ,  7160.659822  ,
       15230.4591676 , 34548.5040338 ,  5832.0521995 , 11815.4601517 ,
        6084.7800672 , 37003.1037225 ,  8145.1197256 ,  7480.52734   ,
       13136.1925762 , 10768.0065109 ,  3522.7504349 ,  8993.680903  ,
        2913.0363887 ,  6708.8863774 , 19435.1082355 , 46374.6726425 ,
        4394.4134482 ,  3973.7007574 ,  6702.8610439 ,  1773.0295734 ,
        8473.2108915 ,  3233.87986892, 10223.4694844 , 10652.8477147 ,
        8884.6382438 , 24902.709863  , 45994.591824  , 16844.9576809 ,
        6522.7804915 , 11185.0571325 , 44108.7785468 ,  9524.6840676 ,
       39688.4779757 ,  1746.645308  , 38224.6793504 ,  5701.4252838 ,
       12939.4433147 ,  5785.2508533 , 40071.6220926 ,  6359.6318164 ,
       10215.7882352 , 10079.3840519 ,  2767.8910186 , 18007.7924512 ,
       12110.9849213 , 10698.4075485 , 13534.9125997 , 15678.5430869 ,
        7900.3575764 ,  5188.8721864 ,  9565.7639242 , 22146.8848329 ,
        4845.4675674 ,  1630.6596945 ,  2490.608386  , 47094.6428244 ,
       11224.8150713 ,  4544.1126278 , 16586.4369284 , 13666.0772338 ,
       34597.466562  ,  6995.6715565 ,  5403.668012  ,  9640.0547815 ,
        2995.658512  ,  3581.4320087 , 21387.6778885 , 16605.1508623 ,
       13836.4449522 ,  2985.7086504 ,  3307.1144562 , 14041.6667365 ,
       10890.7855755 , 15074.0403185 , 20198.639043  ,  9691.0384909 ,
       16657.6518423 ,  2011.5982095 , 13923.4040434 ,  9345.2615478 ,
       15587.4110345 ,  2425.6983413 ,  7111.3994221 , 46865.7002204 ,
        3480.0522775 ,  5325.8754177 ,  1850.5282375 , 12535.2437559 ,
        6753.2019002 , 12002.263502  , 46675.4451951 , 17773.978684  ,
        9127.7968137 , 44211.9369388 , 15275.9041401 , 11291.390461  ,
       10453.2325776 ,  6208.0661371 , 28422.5784295 ,  4828.0095406 ,
       14502.0867945 ,  2523.8363554 , 16522.04288   ,  3391.1699653 ,
       24536.08554   , 14071.860713  ,  6979.742091  , 40507.6540954 ,
        6604.6436803 ,  5268.5521575 , 29373.104977  ,  2922.3960939 ,
       11055.0674745 ,  3929.1421464 , 12047.7259802 ,  3509.0553295 ,
        8160.2203704 ,  6087.474748  , 46161.5888115 ,  9684.169322  ,
       46169.9019787 , 38568.2697045 ,  5839.3067715 , 10937.7751847 ,
        1714.1017709 ,  5598.8043209 ,  3136.3276317 ,  9965.5500408 ,
       45798.7443154 , 11456.857946  ,  1957.395119  , 13532.3608424 ,
        2344.587824  , 12619.7565808 ,  9163.7245003 ,  2541.9062457 ,
        3608.7147638 , 36909.727671  ,  6671.8157244 ,  1917.759027  ,
       41073.4259967 , 12327.088953  , 43018.9834814 , 11757.44503   ,
        7586.2949597 ,  3113.9957317 ,  2051.676715  , 15642.0558382 ,
        5199.6087697 ,  1896.020732  , 11988.2507637 ,  7260.018139  ,
        6221.7948872 ,  5452.0877378 ,  8313.4783167 , 42581.2522109 ,
        4778.6032614 , 12491.4769344 ,  8307.03187408, 19414.1971774 ,
       10983.859994  ,  8056.6060615 , 17424.4296348 , 12564.2379092 ,
       20081.9672295 , 19230.5197007 ])

In [24]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [25]:
r_score

0.8539559690133178