In [3]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset = pd.get_dummies(dataset,dtype = int)

In [6]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='str')

In [8]:
indepentVar = dataset[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]

In [9]:
indepentVar

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0           1         0          0           1
1      18  33.770         1           0         1          1           0
2      28  33.000         3           0         1          1           0
3      33  22.705         0           0         1          1           0
4      32  28.880         0           0         1          1           0
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3           0         1          1           0
1334   18  31.920         0           1         0          1           0
1335   18  36.850         0           1         0          1           0
1336   21  25.800         0           1         0          1           0
1337   61  29.070         0           1         0          0           1

[1338 rows x 7 columns]

In [10]:
depententVar = dataset[['charges']]

In [11]:
depententVar

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepentVar,depententVar,test_size=0.30,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [22]:
from sklearn.svm import SVR
regressor = SVR(kernel = "linear")
regressor.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='linear')

In [23]:
regressor.intercept_

array([9697.29970563])

In [24]:
regressor.n_support_

array([936], dtype=int32)

In [25]:
y_pred = regressor.predict(x_test)

In [26]:
y_pred

array([ 9655.23334037,  9426.86756447, 11989.69225494, 10002.62964445,
        9432.52627213,  8958.39381214,  8419.81395039,  9669.30537141,
        9184.78647186,  9017.84998278,  8951.22918432,  9520.64021135,
        9299.83350011,  8896.03290499, 11141.10023348,  9561.71484188,
        9842.09507682,  8819.03199677,  9208.72558877, 10930.20058279,
       11945.48498818,  9787.36357864,  9581.85503221, 11738.20518711,
        8675.33109322,  9060.75779337,  8667.53294276,  9276.02313324,
        8843.08653337,  9450.65670652,  9236.91622592, 12334.00589288,
       10026.69834524,  9795.0656822 , 10913.78024685,  8829.99680193,
        9553.25679544, 11269.21385176, 11599.2924457 ,  8549.11406333,
        8954.49261185,  8853.15773296, 11517.66566236, 12286.54440348,
       10864.1864137 ,  8623.39320529,  9558.72057751,  9290.37509662,
        8799.16372005,  9707.5688325 ,  8662.19641105,  8537.84441375,
       11852.21138536, 12024.1221096 ,  9879.74596948,  8888.20306957,
        8822.14544945,  9531.45116514,  9410.01034206,  9865.5670623 ,
        8530.44602853, 12386.6923708 ,  9992.26734771,  9631.83821825,
        9643.03015387,  9650.62544136, 10893.29283934, 11396.80230646,
        8525.48983406,  9336.24482526,  9854.23017119,  9799.53095923,
       10899.48668922,  9998.63770888,  9783.47816688,  9815.37161914,
        9362.31592909,  9419.46528596, 11411.42730952, 12356.01153272,
        9694.73439229, 11773.04286906,  8660.26903611,  9424.50803017,
       11750.55934989, 11389.73422381,  8852.91970867,  8782.63023335,
        9861.46012395, 11301.68250226,  9049.94683958,  9727.92157218,
        8786.73292158,  9370.44479904,  9079.0717396 ,  8952.14574206,
       12083.82713379, 11763.80209887,  8953.86277648,  9855.24702594,
        8697.31288248,  9160.70737551,  8857.02204457, 11491.55308417,
       11704.20359851,  8672.49953279,  9690.10880942,  8826.13821885,
        9871.85391639, 12267.82143931,  9632.85597141,  9080.77950455,
        9455.38229416, 10873.76090275, 12277.06716878,  9312.1231117 ,
        8526.08613246,  9533.17513553,  9948.5659964 ,  9463.99019079,
       11806.6675845 ,  9468.07298631, 10057.45802336,  9042.64223232,
        9311.0177906 ,  8774.15921339, 11746.2068067 , 11730.48073265,
       12332.24349081,  8670.40753731,  9355.44962663,  8566.96004429,
        9142.19779453,  9528.2085455 , 11649.12190505, 11392.69465895,
       11600.48779293,  9496.32315529, 11914.5277587 ,  8673.60252038,
        8536.59259417,  9707.46076569,  9646.15054251,  9721.04720768,
        9017.20719066, 10023.6137625 ,  9887.27239559,  8603.11620287,
        8467.43037393,  9678.14633305,  9111.12095983, 11264.7724253 ,
        9641.32699137,  8533.02504815,  8596.92462193,  9200.13460676,
        8676.84514001,  8527.03651942,  9561.35190074,  9515.05072191,
        8899.79871151, 10049.65437204,  9799.85588561,  9708.47110139,
        8828.68347383,  8833.87025835, 10759.68321734,  8956.64711725,
        8932.97866319,  8542.35195117,  8881.49863722,  8858.43035807,
        9330.42820537,  8760.21628473,  8879.06569917,  8867.1032228 ,
        8817.91705385,  9150.9795166 , 12278.32825785,  8474.12093435,
        9636.55686992,  9213.89056398,  9831.13529103,  8839.1367981 ,
        9014.81962025, 12278.34906575,  8656.82109532,  8542.93946158,
        9996.34780972,  9552.32834246, 11929.36716314,  8763.15405996,
        9032.81407639, 11796.25616828,  8791.04476416,  8668.93658923,
        9180.93674135,  9075.14973141,  8984.93919427,  8948.49439672,
        9684.17831282, 12409.46388436,  9744.92098288, 11319.76805051,
        8934.49037647, 11841.52422233,  8741.44639315,  9667.14811558,
        9113.69764593,  8627.32746105,  9542.44471557,  9919.22048497,
        8819.83749282,  8648.90369197,  9279.96205604,  8647.16012111,
        9150.76032352,  8899.76996624,  9855.36740491,  9011.12374111,
        9123.62622354,  9154.82231114,  9432.09177925,  8624.67970471,
        9799.80818445, 10097.20199427,  9820.84489836,  9728.12731025,
        9158.33905323,  8701.35293612,  8510.5511508 ,  9541.17208808,
        9851.82335265,  8559.38710769,  8880.55560313,  9334.28403801,
        9441.59053102, 11065.49155797,  9174.04779575,  9597.11087205,
        9090.68860636, 11045.43976941,  9322.71337273,  9232.62710784,
        9404.75923401,  9696.90468622,  8616.49924032,  9342.29761293,
        8523.21147332,  9235.86470811, 11206.334717  , 12352.17261468,
        8801.98876142,  8817.5090974 ,  8445.67350628,  8445.67542288,
        9456.26537951,  8515.40357188,  8803.90609763,  8711.75945765,
        9382.07774658, 11858.47253686, 12326.62023673,  9954.95864837,
        9276.37801233,  9888.02631397, 11350.09323577,  9455.37033883,
       11615.40752031,  8549.47658755, 11074.30094255,  9064.85779575,
        9816.88333242,  8701.79315752, 11522.0116865 ,  9033.58299279,
        9675.15667114,  9464.95288992,  8620.40545997,  9849.27816225,
        9746.00216116,  9089.41556196,  9890.3662478 ,  8454.29335824,
        9255.93638938,  8768.99913288,  9301.98340306, 11606.60590553,
        8946.42433523,  8468.08703798,  8504.03052253, 12300.75182828,
        9516.79048084,  8929.52880581,  9751.81686445,  9718.00105662,
       10979.53947703,  9178.26740336,  9097.62250269,  9620.28100798,
        8547.59499717,  8632.39943205, 10996.47625314, 11051.0435477 ,
        9902.7973986 ,  8705.70822975,  8727.68116644,  9446.9534745 ,
        9659.43561646, 10726.35951761, 11396.34402759,  9098.83164049,
       10799.17691637,  8490.70205762,  9340.48709279,  9074.8525489 ,
        9357.57426067,  8481.64042449,  9297.27791415, 11740.2205469 ,
        8673.59366781,  8795.09981582,  8418.29530115,  9472.28750998,
        8865.99485902,  9706.07863628, 12376.17903322, 11236.93133885,
        9566.78562221, 11802.15927334,  9824.63426322,  8937.93831726,
        9620.73008195,  8808.92265775, 12210.9069827 ,  8934.45236171,
        9798.33723636,  8516.71654765, 10817.32397313,  8646.43465576,
       12070.60667561,  9252.49346796,  8649.47387085, 11105.99600962,
        8927.36113764,  9012.06414943, 12289.03543825,  8545.87102678,
        9379.76166333,  8564.36948626,  9609.63305037,  8647.85796727,
        9193.65886463,  8989.47135601, 12048.93708365,  9376.74325613,
       11354.78230833, 11082.51900478,  9176.2708102 ,  9381.47176178,
        8522.59742648,  8696.36291243,  8538.50801377,  9582.0960346 ,
       12129.79453368,  9737.58721342,  8438.12096066,  9812.58225901,
        8604.03276061,  9371.31832265,  8886.02082031,  8782.15037284,
        8788.72641198, 10954.13084713,  9095.80552808,  8369.68270609,
       11571.93994317,  9776.52723127, 11997.86076399,  9766.91856067,
        9028.86434111,  8571.68988205,  8509.87105308,  9569.45579403,
        9066.7725062 ,  8470.67107697,  9604.46503248,  9164.73397414,
        9272.21112524,  8758.02751642,  8600.99546212, 11371.31029417,
        8619.55041074,  9468.0706528 ,  8527.38062934,  9370.53780326,
        9848.89555607,  8926.7824798 , 11011.81774431,  9803.95774001,
       10132.06125786,  9858.15563897])

In [27]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [28]:
r_score

0.06034893525376839