In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [6]:
indep = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [7]:
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dep = dataset[['charges']]

In [9]:
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(indep,dep,test_size=0.30,random_state=0)

In [11]:
from lightgbm import LGBMRegressor
regressor = LGBMRegressor(
    objective="regression",
    n_estimators=100,
    learning_rate=0.1,
    num_leaves=31,
)

In [12]:
# Fit the model
regressor.fit(x_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000427 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 192
[LightGBM] [Info] Number of data points in the train set: 402, number of used features: 5
[LightGBM] [Info] Start training from score 13357.749206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(objective='regression')

In [13]:
y_pred = regressor.predict(x_test)

y_pred

array([ 3.93282011e+03,  5.97054276e+03,  1.40323439e+04,  6.49793755e+03,
        7.68495974e+03,  3.84460509e+03,  3.64166207e+04,  1.36789251e+04,
        8.14620406e+03,  1.37454370e+04,  1.01724858e+04,  1.60770272e+04,
        4.54759982e+04,  4.88498571e+03,  8.02876042e+03,  1.39792387e+03,
        1.45400944e+04,  6.62211075e+02,  7.35014481e+03,  3.14151641e+03,
        1.64763001e+04,  4.65732217e+03,  1.23100415e+04,  4.31772730e+04,
        4.33086838e+03,  3.39588345e+04,  1.89475705e+04,  1.69156864e+04,
        7.15028205e+03,  3.82932653e+04,  1.29579080e+04,  3.33755306e+03,
        1.22680399e+04,  1.99130091e+04,  3.72519967e+04,  2.12656785e+04,
        9.70202400e+03,  3.88003426e+04,  7.03898263e+03,  1.93251282e+04,
        5.72525924e+03,  3.59587631e+04,  4.53442929e+03,  1.22285083e+04,
        3.64604132e+03,  4.38004573e+04,  8.81736338e+03,  1.16183883e+04,
        9.01479598e+03,  8.22008436e+03,  9.90258729e+03,  7.50284259e+03,
        1.60846287e+04,  2.85732951e+03,  1.13511373e+03,  1.18204796e+04,
        7.65324953e+03,  6.52664527e+03,  3.67533871e+04,  1.24309908e+04,
        7.06521471e+03,  1.01971318e+04,  1.23406677e+04,  2.39277300e+02,
        1.18992399e+04,  1.10108096e+04,  8.32626274e+03,  2.27344933e+03,
        4.47189685e+04,  1.10897853e+04,  7.83794544e+03,  8.39161400e+03,
        1.51665834e+04,  5.08579348e+03,  1.27708890e+04,  2.04712732e+04,
        3.16072963e+04,  1.05578720e+04,  1.14158646e+04,  4.58865664e+03,
        4.80031746e+03,  8.80808775e+03,  5.01517361e+03,  9.40967177e+03,
        4.18594992e+03,  3.05365610e+03,  3.94504514e+04,  5.34521274e+03,
        7.60235299e+03,  6.80968838e+03,  2.11869727e+04,  1.11895561e+04,
        1.15461093e+04,  6.77849802e+03,  5.77318111e+03,  8.52496012e+03,
        1.62594235e+03,  9.12767247e+03,  2.16838562e+04,  6.21617665e+03,
        4.38671743e+04,  1.05505271e+04,  9.65287096e+03,  3.29856039e+03,
        6.34310450e+03,  3.77201338e+04,  1.34692186e+03,  8.20632658e+03,
        1.10234672e+04,  8.78098944e+03,  3.14151641e+03,  1.27597423e+04,
        1.81318817e+04,  3.54900241e+04,  1.52890566e+04,  8.13082888e+03,
        1.33118405e+04,  1.51665834e+04,  3.55696655e+04,  1.05490045e+04,
        1.49141385e+04,  1.38233801e+04,  3.39984400e+03,  3.56429139e+04,
        4.96784024e+03,  2.40043768e+04,  7.60342330e+03,  2.91604828e+03,
        1.06379769e+04,  1.32847077e+04,  5.35623610e+03,  1.96053656e+03,
        1.10832940e+03,  1.89432298e+03,  9.98905845e+03,  8.71674792e+02,
        1.25764234e+04,  4.44734379e+03,  6.42933717e+03,  1.36273962e+04,
        1.34601930e+04,  6.23042771e+03,  1.49006605e+04,  2.39758067e+03,
        1.19752780e+04,  3.67754848e+03,  6.67658498e+03,  1.31717425e+04,
        1.48593748e+04,  2.25491811e+04,  1.72475162e+04,  9.36534989e+03,
        7.41841710e+03,  1.09744795e+04,  5.87083391e+03,  1.28342551e+04,
        1.04495532e+04,  5.60226537e+03,  2.16180465e+04,  1.62342671e+04,
        1.34394670e+04,  1.80034100e+04,  1.05522696e+04,  8.23319829e+03,
        9.87138859e+03,  1.17740602e+04,  1.04294184e+04,  1.61570755e+03,
        7.36588814e+03,  6.44717354e+03,  4.34271816e+03,  1.96981839e+04,
        3.22133508e+03,  4.94443205e+03,  3.19500257e+03,  3.24102888e+03,
        7.62672575e+03,  4.22447757e+03,  1.28445300e+04,  3.86176080e+04,
        1.32279023e+04,  9.00201331e+03,  4.32613876e+04,  3.14151641e+03,
        1.34782152e+04,  2.37884641e+03,  6.37285430e+03,  2.00631109e+04,
        1.01753756e+04,  5.05741768e+03,  1.48735579e+04,  1.28777211e+04,
        3.77550053e+04,  1.49390625e+04,  5.61102008e+03,  1.28395720e+04,
        1.82193538e+04,  1.97297388e+03,  1.07559268e+04,  6.80968838e+03,
        3.64604132e+03,  2.50046219e+04,  2.34577340e+04,  1.08163311e+04,
        4.89522644e+03,  9.99888171e+03,  2.36266522e+04,  2.32742093e+04,
        8.74851826e+03,  1.92643996e+04,  4.35917850e+04,  3.53163247e+03,
        2.17554913e+04,  9.04873331e+03,  2.42644495e+04,  2.07517861e+04,
        1.64236363e+04,  1.04690389e+04,  6.41128565e+03,  1.59998885e+04,
        1.28395720e+04,  1.61658756e+03,  1.21524245e+04,  1.40323439e+04,
        3.76949060e+03,  6.72279526e+03,  2.25297081e+04,  1.28630429e+03,
        7.07339494e+03,  1.27825623e+04,  1.37492503e+04,  7.80209239e+03,
        1.61570755e+03,  4.56363688e+04,  3.94513949e+03,  1.27616806e+04,
        4.73461279e+03,  2.74110972e+03,  4.72624919e+03,  1.31997819e+04,
        1.41789891e+04,  5.94596091e+03,  4.60862100e+04,  7.77228864e+03,
        1.16113280e+04,  1.45252418e+03,  9.89874269e+03,  1.89986961e+04,
        6.21035490e+03,  2.90886672e+03,  6.76883157e+03,  1.60329400e+04,
        7.44137368e+03,  1.33671480e+04,  1.16501641e+04,  1.53350532e+04,
        3.85079991e+03,  1.65069510e+03,  2.20600167e+03,  3.49979785e+04,
        6.69582170e+03,  1.49061708e+04,  3.99839670e+03,  4.10152479e+04,
        5.51838851e+03,  7.26031221e+03,  8.58705234e+03,  1.37863521e+04,
        6.78338319e+03,  8.71674792e+02,  5.31331553e+03,  1.30687486e+04,
        7.99046548e+03,  3.14052687e+03,  2.23978369e+04,  1.55132478e+04,
        1.69156864e+04,  2.50250199e+03,  4.09507852e+03,  1.50640275e+04,
        1.93446713e+03,  3.05169283e+03,  1.21734672e+04,  1.58564905e+04,
        2.00861983e+02,  8.73638742e+03,  1.15713214e+04,  9.12938826e+03,
        7.87440620e+03,  3.79755306e+03,  6.06569803e+03,  1.80099730e+04,
        1.19170200e+04,  4.84141187e+04,  1.31252488e+04,  2.17807700e+04,
        1.68340384e+04,  1.29907395e+04,  6.79902810e+03,  7.77736196e+03,
        6.73493370e+03,  7.84636902e+03,  1.41563631e+04,  4.78947957e+03,
        5.46241983e+03,  3.81903212e+01,  1.20885690e+04,  3.99027690e+03,
        1.47080260e+04,  9.97295040e+03,  5.75471808e+03,  1.37155764e+04,
        2.19525432e+04,  1.23852789e+04,  1.45133744e+04,  2.08243441e+04,
        5.14885961e+03,  1.13462270e+04,  9.87086029e+03,  4.73295812e+02,
        8.97235182e+03,  1.80720740e+03,  8.30921656e+03,  1.61921866e+04,
        1.01211517e+04,  4.87237604e+03,  6.20853237e+03,  1.55132478e+04,
        6.70341495e+03,  1.72955304e+03,  2.20396698e+03,  9.68284158e+03,
        1.10151217e+04,  4.09475252e+03,  6.08869070e+03,  6.60915958e+03,
        7.82832023e+03,  4.39707907e+04,  1.08873677e+04, -1.82369545e+02,
        1.43264456e+04,  9.23638149e+03,  8.30670951e+03,  8.66273983e+03,
        1.38581253e+04,  3.77543766e+03,  9.76531969e+03,  9.08196405e+03,
        3.65843953e+04,  1.64081679e+04,  7.29792659e+03,  3.17603832e+03,
        1.65069510e+03,  1.61947290e+04,  7.31434370e+03,  1.12213873e+04,
        6.77640148e+03,  1.94364224e+04,  1.39092218e+04,  4.53210046e+04,
        1.44100396e+04,  1.38117876e+04,  4.57466683e+03,  2.09737131e+04,
        4.72624919e+03,  6.08364823e+03,  6.32117924e+03, -3.34901477e+02,
        9.75319751e+03,  4.69648676e+04,  2.30164672e+04,  1.20204082e+03,
        1.43136918e+04,  4.00071707e+04,  4.61795497e+03,  1.96217552e+04,
        6.15043220e+03,  8.63054491e+03,  1.05197874e+04,  7.45473907e+03,
        4.13671805e+03,  1.22322162e+04,  1.36011037e+04,  2.27770240e+03,
        1.16309657e+04,  1.43134455e+04,  1.78646016e+04,  1.50120548e+04,
        2.01241237e+04,  2.15528880e+04,  7.25224951e+03,  8.65468031e+03,
        4.12107032e+04,  1.69988351e+04,  8.67092899e+03,  1.43478271e+04,
        9.01375736e+03,  8.23237217e+03,  5.95371694e+03,  4.84829551e+03,
        2.20413666e+04,  8.37511370e+03,  1.24028345e+04,  1.65069510e+03,
        6.47171152e+03,  2.25787353e+03,  1.06099045e+04,  7.17131840e+03,
        6.88170451e+03,  3.91003356e+04,  1.38043315e+04,  1.26587584e+03,
        1.18286165e+04,  1.39433221e+04,  7.69647563e+03,  1.49902756e+04,
        1.19178358e+04,  9.71603128e+03,  5.75922290e+03,  5.91986987e+03,
        3.77005223e+03,  4.66642794e+04,  1.41913178e+04,  1.34879900e+04,
        5.33042941e+03,  1.23697306e+04,  1.48363694e+04,  1.97297388e+03,
        8.36377620e+03,  1.65802142e+04, -5.60626126e+02,  1.30939837e+03,
        7.68061982e+03,  3.19463566e+03,  5.53426321e+03,  1.04427644e+04,
        6.26962834e+01,  1.85123002e+04,  1.29361412e+03,  4.09019877e+03,
        4.95442088e+03,  8.36757314e+03,  1.54830240e+03,  1.51632761e+04,
        1.51753468e+04,  1.99789975e+04,  4.06890423e+04,  4.14620594e+03,
        4.57927750e+04,  3.25045546e+03,  1.11834093e+04,  4.33086838e+03,
        4.44125536e+03,  3.82107406e+04,  1.30306327e+04,  9.47121791e+03,
        5.88751810e+03,  1.98789758e+03,  1.42576417e+04,  2.23439572e+04,
        2.08339769e+03,  7.04020810e+03,  1.10832940e+03,  1.17567503e+04,
        1.61900840e+04,  3.05723468e+03,  5.10796102e+03,  1.49958819e+04,
        1.58021754e+04,  1.36225276e+04,  3.44211406e+04,  1.55138783e+04,
        8.92797427e+03,  1.20706267e+04,  1.13502853e+04,  1.06799673e+04,
        1.36043161e+04,  2.08037124e+04,  3.87490178e+04,  1.21870750e+04,
        9.65562776e+03,  1.92734712e+04,  6.43990003e+03,  5.55696377e+03,
        6.54561375e+03,  7.23334246e+03,  4.80019273e+04,  4.28610528e+04,
        3.37269266e+04,  1.37863521e+04,  4.62948586e+04,  4.81814091e+04,
        3.17052504e+03,  1.69853672e+04,  3.32540168e+03,  2.63573014e+04,
        5.87083391e+03,  1.15676512e+04,  2.46884843e+03,  4.14061570e+04,
        1.66249511e+04,  8.04217076e+03,  1.31079515e+04,  3.94302519e+03,
        8.60118084e+03,  3.81096126e+04,  7.32082926e+03,  1.73973720e+04,
        1.02806415e+04,  2.62482553e+03,  3.95643850e+04,  1.34042937e+04,
        5.06849890e+03,  1.69182362e+04,  2.01191850e+04,  7.72729848e+03,
        2.08339769e+03,  1.61269115e+03,  9.60776366e+03,  4.96037916e+03,
        2.86439359e+03,  1.17583688e+04,  6.36388387e+03,  3.83945366e+04,
        1.08391367e+04,  3.70658313e+03,  4.05149626e+03,  2.17050995e+04,
        1.23080037e+04,  5.34784581e+03,  4.42460894e+04,  7.92285347e+03,
        4.48553411e+04,  7.08792312e+03,  1.14491712e+04,  2.60670955e+03,
        3.87150649e+04,  9.18566470e+03,  1.31736972e+04,  1.41416412e+04,
        8.11702777e+03,  2.45186883e+04,  1.08219562e+04,  1.44204741e+04,
        1.27050917e+04,  4.35913963e+04,  4.48319880e+03,  2.19767290e+04,
        1.34524379e+04,  4.76648989e+03,  4.71601780e+03,  1.34853061e+04,
        1.09172143e+04,  2.91668314e+03,  1.23715504e+04,  2.16873409e+03,
        5.78945442e+03,  1.36099383e+04,  9.02938089e+02,  1.22102725e+04,
        3.99585376e+04,  1.00982203e+04,  2.09737131e+04,  3.19670530e+04,
        1.15718176e+04,  1.39200512e+04,  1.84580149e+04,  6.16953591e+03,
        2.04504160e+04,  1.31131181e+04,  1.90977119e+04,  5.69842505e+03,
        1.95941930e+03,  3.68499038e+04,  8.31467091e+03,  2.28703557e+04,
        2.15170952e+04,  3.88277164e+04,  1.57948136e+03,  1.15090008e+04,
        1.26610726e+04,  5.87244465e+03,  4.15347151e+04,  1.95105142e+04,
        1.03398646e+04,  2.20772729e+04,  1.03366977e+04,  3.01701661e+03,
        7.55869690e+03,  1.97855991e+04,  6.75691216e+03,  1.58007869e+04,
        1.53412773e+04,  4.64719741e+03,  4.49125151e+03,  3.47772791e+03,
        2.28564967e+04,  4.24722614e+03,  6.33934316e+03,  1.36704610e+04,
        1.38712246e+04,  8.55664775e+03,  4.78263941e+03,  1.45109422e+04,
        8.33811676e+03,  6.37155434e+03,  6.84806754e+03,  3.65401789e+04,
        2.19582353e+04,  9.84808492e+03,  7.66988493e+03,  1.00235845e+04,
        3.91162762e+03,  5.55766404e+03,  1.55132478e+04,  3.79863314e+04,
        1.36584892e+04,  1.32816982e+04,  6.06569803e+03,  1.56444043e+04,
        2.29730423e+03,  1.04096914e+04,  1.47067869e+04,  1.44070888e+04,
        7.29731896e+03,  1.34014546e+04,  5.89715860e+03,  1.64399945e+04,
        6.88178881e+03,  7.53322506e+03,  3.35641528e+03,  2.52304876e+03,
        1.12534259e+04,  5.74290468e+02,  4.61376377e+03,  7.89355199e+03,
        1.63161259e+04,  6.08013517e+03,  7.07112940e+03,  3.84092224e+04,
        4.26651748e+03,  8.10977031e+03,  1.26348685e+04,  5.38114357e+03,
        1.13479012e+04,  1.39580108e+04,  1.40149609e+04,  1.14909108e+04,
        9.61377039e+03,  1.66348645e+04,  9.22798068e+03,  8.39841975e+03,
        2.52391921e+04,  4.78389791e+03,  7.32483925e+03,  4.72567716e+04,
        1.10012909e+04,  9.78112231e+03,  1.39629709e+04,  6.78335590e+03,
        4.70810350e+04,  4.15697272e+04,  1.46528059e+04,  1.65069510e+03,
        1.11895804e+04,  2.18798667e+04,  1.96183780e+04,  1.21352918e+04,
        4.01948569e+03,  5.25276713e+03,  1.45849494e+04,  3.12967243e+03,
        2.81711458e+03,  7.09861316e+03,  2.10285251e+04,  2.26038496e+04,
        3.98118995e+04,  1.67924428e+04,  1.46197976e+04,  1.03722173e+04,
        4.70810350e+04,  5.58739318e+03,  4.87429412e+03,  1.62408337e+04,
        7.93615556e+03,  4.11637143e+04,  1.36778799e+04,  1.10063809e+04,
        1.28433989e+03,  4.05818122e+03,  4.56757551e+03,  1.50303710e+04,
        2.23936547e+04,  8.29377226e+03,  4.49735312e+03,  1.98189947e+04,
        2.32204843e+04,  1.27708890e+04,  3.75361447e+03,  1.25959592e+04,
        4.10080464e+04,  2.92086958e+04,  3.74983461e+04,  5.19091902e+03,
        1.55487562e+04,  8.40875930e+03,  2.41139620e+03,  7.17607859e+03,
        3.19266283e+03,  5.94522246e+03,  5.64217768e+03,  7.19541319e+03,
       -1.82369545e+02,  5.92248163e+03,  1.38269654e+04,  8.54144561e+03,
        7.00961441e+03,  1.44694465e+04,  6.23979233e+03,  8.71674792e+02,
        1.04739018e+04,  1.30838402e+04,  2.22531630e+04,  3.37269266e+04,
        1.35728642e+04,  7.09018113e+03,  1.25431351e+04,  1.79885892e+04,
        1.55138783e+04,  5.50763411e+03,  4.24466378e+03,  9.67856996e+03,
        2.09256626e+04,  5.61923712e+03,  2.29974630e+04,  1.20298452e+04,
        5.22803651e+03,  1.47852167e+04,  2.48703682e+04,  1.28630429e+03,
        3.24102888e+03,  9.75881436e+01,  1.05993576e+04,  3.48995471e+04,
        8.81712472e+03,  1.47777489e+04,  5.19502760e+03,  1.29989490e+04,
        1.85799002e+04,  1.36584892e+04,  4.53603534e+04,  2.57887517e+04,
        1.06181990e+04,  2.48913367e+04,  8.95739119e+03,  6.30662271e+03,
        7.35393472e+03,  1.43124879e+04,  1.26744154e+04,  9.26724834e+03,
        7.28599228e+03,  1.15104445e+04,  8.92579831e+03,  3.77049322e+03,
        2.27723959e+04,  1.81433507e+03,  8.05195760e+03,  8.31921564e+03,
        2.38448492e+03,  1.55277734e+04,  5.24520153e+03,  1.38084081e+03,
        1.10791244e+04,  1.55138783e+04,  8.80365566e+03,  9.11423537e+03,
        2.88748610e+04,  4.61800127e+04,  1.47805322e+04,  3.04249554e+03,
        4.96359086e+03,  9.35650527e+03,  2.33162850e+04,  1.36948278e+04,
        2.83701479e+04,  1.27379151e+04,  7.57077156e+03,  1.29883917e+04,
        2.38587570e+03,  4.20866812e+03,  8.31921564e+03,  1.69156864e+04,
        1.20411081e+04,  7.71577438e+03,  2.15488014e+04,  3.12201281e+03,
        2.01079371e+04,  4.53177062e+04,  1.12601529e+04,  5.02731347e+03,
        8.92315870e+03,  4.23022458e+04,  2.50446082e+04,  5.11734798e+03,
        9.68840293e+03,  7.15469255e+03,  4.28486143e+04,  1.38963247e+04,
        1.32662772e+04,  2.75983840e+03,  7.34199371e+03,  1.43379223e+04,
        2.31924568e+04,  4.83515744e+03,  5.69424708e+03,  4.51757689e+04,
        6.15619845e+03,  5.08310456e+03,  6.21505253e+03,  5.91849496e+03,
        1.09542793e+04,  1.11882646e+04,  2.23284740e+03,  5.97876941e+03,
        1.63292487e+04,  4.00242661e+04,  6.62372428e+03,  4.07400605e+04,
        1.45432045e+04,  8.34856794e+03,  2.02083246e+04,  3.83433174e+04,
        1.45494465e+04,  3.77672213e+04,  6.07496646e+03,  7.95476098e+03,
        1.36043161e+04,  6.44014084e+03,  1.17652718e+04,  1.98660030e+04,
        7.31741254e+03,  4.19554594e+03,  1.48118380e+04,  5.17317799e+03,
        4.50947869e+04,  1.17852526e+04,  4.23362516e+03,  4.68008942e+03,
        8.03697322e+03,  3.69191925e+04,  1.99443442e+04,  1.36393093e+04,
        3.29257150e+03,  2.24194633e+04,  1.65069510e+03,  7.12278615e+03,
        2.12842804e+04,  1.30630034e+04,  2.42110234e+03,  7.01210278e+03,
        5.99561188e+03,  1.49006605e+04,  1.41197523e+04,  6.07772163e+03,
        1.48261532e+03,  3.63324842e+04,  3.83163835e+04,  1.01054151e+04,
        1.40814189e+04,  5.55494559e+03,  1.75137866e+04,  1.60536530e+04,
        8.89092799e+03,  2.40026507e+03,  1.25870156e+04,  7.58192881e+03,
        2.19822072e+03,  3.32485655e+04,  7.02827947e+03,  7.72063834e+02,
        3.97268859e+04,  1.28467944e+04,  2.46076535e+03,  1.29499673e+04,
        9.88092143e+03,  8.91856279e+03,  6.19625035e+02,  7.35014481e+03,
        1.89475705e+04,  5.74559312e+03,  7.04524074e+03,  3.94472921e+04,
        9.74415862e+02,  1.05178787e+04,  6.11566179e+03,  8.66273983e+03,
        2.49375069e+04,  4.84829551e+03,  4.76405113e+04,  1.34537508e+04,
        1.14491712e+04,  4.05303504e+04,  7.18459708e+03,  2.45632515e+03,
        2.97579951e+03,  2.26445373e+04,  1.37433653e+04,  6.07092443e+03,
        4.09999087e+03,  8.53426189e+03,  1.89974559e+04,  3.71120245e+04,
        4.87567565e+03,  6.18225081e+03,  1.35266712e+04,  1.39629709e+04,
        8.45809407e+03,  1.52755860e+04,  4.71951019e+04,  8.42615250e+03,
        1.06609335e+04,  8.83536646e+03,  1.20706267e+04,  4.35172982e+03,
        6.68815304e+03,  3.51180688e+04,  2.09588329e+03,  1.08126623e+04,
        1.18044245e+04,  2.98115099e+03,  1.65568342e+04,  1.37299426e+03,
        7.72729848e+03,  5.84292608e+03,  6.05390995e+02,  6.92876531e+03])

In [14]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [15]:
r_score

0.8187783138914216